[package]
name = "remnantsofsiren/cardinal"
version = "0.0.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["src"]
private = true

[dependencies]
bridgenet2 = "ffrostflame/bridgenet2@1.0.0"
promise = "evaera/promise@4.0.0"
lemonsignal = "data-oriented-house/lemonsignal@1.10.0"
trove = "sleitnick/trove@1.2.0"