[package]
name = "emery/cardinal"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
red = "uncontained0/red@1.2.2"
signal = "sleitnick/signal@2.0.1"
promise = "evaera/promise@4.0.0"
squash = "data-oriented-house/squash@1.1.6"