[package]
name = "remnantsofsiren/cardinal"
version = "1.8.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
description = "A simple Framework, more like module loader, for creating Roblox games. Uses Libraries like BridgeNet, Promise, Signal, and Trove; credit to their original owners."
exclude = ["build", "NetDefinitions.blink", "test.project.json", "rokit.toml", "selene.toml", "test"]

[place]
shared-packages = "game.ReplicatedStorage.Packages"

[dependencies]
Trove = "sleitnick/trove@^1"
Signal = "data-oriented-house/lemonsignal@^1"
Promise = "evaera/promise@^4"