[package]
name = "remnantsofsiren/bridgenet2"
version = "1.0.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
description = "Small patch for bridgnet2 to fix a bug with InvokeServerAsync. Was tired of using wally-patch-package; Sorry for reposting."
license = "MIT"

[dependencies]
TableKit = "ffrostflame/tablekit@0.2.4"
RemotePacketSizeCounter = "pysephwasntavailable/remotepacketsizecounter@2.1.0"
wallyInstanceManager = "ffrostflame/wally-instance-manager@0.1.0"